version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "1500:1500"
    environment:
      NODE_ENV: production
      DB_USER: myuser
      DB_PASSWORD: myuserpassword
      DB_DATABASE: mydatabase
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: always
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: myuserpassword
      MYSQL_ROOT_PASSWORD: mypassword
    ports:
      - "3306:3306"
